### ISSUE TITLE
EOFError with multithreaded mbtiles writing

### ISSUE THREAD

**Issue by bitfag** [Zverik/polytiles#15]
I tried to generate mbtiles file using the following command:

`polytiles.py -z 3 19 -m taxsee.mbtiles -s project.xml --host postgres-osm -d gis -u osm -a 0 --threads 4`

And after ~20 seconds I've got an error:

```
13 5582 2497
13 5579 2497
11 1394 626
Process ThreadedWriterWrapper-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "../polytiles/polytiles.py", line 237, in run
    req, args = self.pipe.recv()
EOFError
```

Everything stuck then.  Using `--threads 1` solves the problem.
Also, issue doesn't shows up whether use plain tiles output to png files (not mbtiles).

**Comment by tobwen** [comment]
Should be fixed in https://github.com/Zverik/polytiles/pull/19
